/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package daggett

class App {
    static void main(String[] args) {
        //  groovy.lang.GroovyRuntimeException: Could not find matching constructor for: daggett.MyClass()
        MyClass blah = new MyClass()
    }
}
